# constants.py

# Screen dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (100, 100, 100)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# Game States
STATE_MAIN_MENU = "MAIN_MENU"
STATE_CHARACTER_SELECT = "CHARACTER_SELECT"
STATE_LEVEL_MAP = "LEVEL_MAP"
STATE_GAMEPLAY = "GAMEPLAY"
STATE_INVENTORY = "INVENTORY"
STATE_LEVEL_EDITOR = "LEVEL_EDITOR"
STATE_CUSTOM_CATALOG = "CUSTOM_CATALOG"
